name: Tests
on: [ push ]
jobs:
    tests:
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.4.0
            -   name: Dependencies
                run: sudo apt-get install -y libgpgme-dev
            -   name: Setup PHP
                uses: shivammathur/setup-php@verbose
                with:
                    php-version: '8.0'
                    coverage: none
                    extensions: 'none, xml, gnupg-1.5.0'
                env:
                    fail-fast: true
