name: Tests
on: [ push ]
jobs:
    tests:
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.4.0
            -   name: Setup PHP
                uses: shivammathur/setup-php@2.16.0
                with:
                    php-version: '8.0'
                    coverage: none
                    extensions: 'none, memcached'

